---
title: "hw2.Rmd"
author: "YangfanCai/yangfanc"
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





R command

1.
```{r}
cel <- 24:15
cel
var(cel)
range(cel)
min(cel)
max(cel)
```


```{r}
convert <- function(fahr)
  cel <- ((fahr - 32) * 5/9)
print(cel)
convert(24.0)
convert(15.0)

var(cel)
range(cel)
max(cel)
min(cel)
```



2.
```{r}
vec <- c()
for (x in c(1:200)) {
  if (x %% 2 == 0) {
    vec <- c(vec, 0)
  }
  else {
    vec <- c(vec, 1)
  }
}
print(vec)

```




3.
```{r}
?round
```


```{r}
numPerfect <- 0
#test <- c()
for (x in c(1:1001)) {
  sqrt <- x^0.5
  if (sqrt == round(sqrt)) {
    numPerfect = numPerfect + 1
    #test <- c(test, x)
  }
}
print(numPerfect)
```



Cars and mileage

```{r}
library(dplyr)
library(ggplot2)
data <- mpg %>%
  group_by(year) %>%
  summarise(averageMPG = mean(hwy))
data
```




```{r}
??mpg
```


```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))
```


```{r}
summary(mpg)
```


```{r}
mpg1999 <- mpg[mpg$year == 1999,]
mpg1999
```


```{r}
sortHwy <- mpg[order(-mpg$hwy), ]
top3 <- sortHwy[1:3, ]
print(top3)
```


```{r}
mpg2008 <- mpg[mpg$year == 2008,]
mpg2008
```



2.
```{r}
CompactModels <-  mpg[mpg$class == 'compact', ]
numCompact <- length(unique(CompactModels$model))
print(numCompact)
```






3.
```{r}
ggplot(mpg, aes(x=hwy, y=cty))+geom_point()
```



```{r}
ggplot(aes(x=hwy, y=cty), data = mpg) +geom_jitter()
```


summary:
relationship with hty and city in mpg is linear and positive.





4.
```{r}
ggplot(aes(x=hwy, y =cty, color = year), data = subset(mpg, year == 2008 | year == 1999), select = c(hwy, cty)) + geom_jitter()
```


```{r}
ggplot(aes(x=hwy, y =cty, color = year, size = cyl), data = subset(mpg, year == 2008 | year == 1999), select = c(hwy, cty)) + geom_jitter()
```


```{r}

summary(mpg[mpg$year == '1999', ][, c('year', 'hwy')])
summary(mpg[mpg$year == '2008', ][, c('year', 'hwy')])

summary(mpg[mpg$year == '1999', ][, c('year', 'cty')])
summary(mpg[mpg$year == '2008', ][, c('year', 'cty')])
```


```{r}
ggplot(aes(x = class, y = cty),data=mpg) + geom_boxplot() + scale_y_continuous(name="city miles per gallon")
hwy1 <- ggplot(mpg, aes(group=year, x=year, y=hwy)) + geom_boxplot()
hwy1
cty1 <- ggplot(mpg, aes(group=year, x=year, y=cty)) + geom_boxplot()
cty1
```

Summary:
No
fuel efficient: 2008<1999
highway and city travel: near

